require("core")
require("modules")
require("modules.keymaps")

require("modules.alpha")
require("modules.colorscheme")
require("modules.bufferline")
require("modules.toggleterm")
require("modules.autocommands")
require("modules.treesitter")
require("modules.nvim-tree")
require("modules.indentline")
require("modules.gitsigns")
require("modules.autotag")
require("modules.telescope")
require("modules.sniprun")
require("modules.impatient")
require("modules.comment")
require("modules.autopairs")
require("modules.attempt")
require("modules.gps")
-- require("modules.lualine_navic")
require("modules.lualine_gps")
require("modules.project")
require("modules.whichkey")
require("modules.rust")
-- require("modules.cmp")
require("modules.dap")
require("modules.flutter")
require("modules.lsp")
-- require("modules.neotest")
require("modules.symbols_outline")
