require("core")
require("modules")

require("modules.cmp")
require("modules.alpha")
require("modules.toggleterm")
require("modules.autocommands") require("modules.plugins")
require("modules.nvim-tree")
require("modules.indentline")
require("modules.gitsigns")
require("modules.keymaps")
require("modules.treesitter")
require("modules.colorscheme")
require("modules.telescope")
require("modules.impatient")
require("modules.comment")
require("modules.autopairs")
require("modules.bufferline")
require("modules.lualine")
require("modules.project")
require("modules.whichkey")
require("modules.lsp")
require("modules.autotag")
--require("modules.trouble")
--require("modules.wilder")
require("modules.sniprun")
