local script = require("core.script")
require("core")
require("modules")
require("modules.keymaps")

-- require("modules.autocommands")
-- require("modules.treesitter")
-- require("modules.nvim-tree")
-- require("modules.gitsigns")
-- require("modules.telescope")
-- require("modules.sniprun")
-- require("modules.impatient")
-- require("modules.comment")
-- require("modules.autopairs")
-- require("modules.attempt")
-- require("modules.gps")
-- require("modules.lualine_navic")
-- require("modules.lualine_gps")
-- require("modules.project")
-- require("modules.whichkey")
-- require("modules.rust")
-- require("modules.cmp")
-- require("modules.dap")
--require("modules.flutter")
-- require("modules.lsp")
-- require("modules.neotest")
-- require("modules.symbols_outline")

script.req("modules.alpha", "alpha")
script.req("modules.impatient", "impatient")
script.req("modules.notify", "notify")
script.req("modules.whichkey", "which-key")
script.req("modules.colorscheme", "nightfox")
script.req("modules.bufferline", "bufferline")
script.req("modules.nvim-tree", "nvim-tree")
script.req("modules.toggleterm", "toggleterm")
script.req('modules.treesitter', "nvim-treesitter", "nvim-treesitter-endwise", "nvim-ts-autotag")
script.req("modules.indentline", "indent_blankline")
script.req("modules.gitsigns", "gitsigns")
script.req("modules.telescope", "telescope")
script.req("modules.comment", "Comment")
script.req("modules.autopairs", "nvim-autopairs")
script.req("modules.gps", "nvim-gps")
script.req("modules.lualine_gps", "lualine", "nvim-gps")
