return {
	{
		"nvim-treesitter/nvim-treesitter",
		dependencies = {
			"JoosepAlviste/nvim-ts-context-commentstring",
			"RRethy/nvim-treesitter-endwise",
			"windwp/nvim-ts-autotag",
			"nvim-treesitter/playground",
			{
				"lukas-reineke/indent-blankline.nvim",
				event = { "BufReadPost", "BufNewFile" },
				opts = {

					char = '▏',
					show_first_indent_level = true,
					filetype_exclude = {
						"", -- for all buffers without a file type
						"dashboard",
						"dotooagenda",
						"flutterToolsOutline",
						"fugitive",
						"git",
						"gitcommit",
						"help",
						"json",
						"log",
						"markdown",
						"NvimTree",
						"peekaboo",
						"startify",
						"TelescopePrompt",
						"todoist",
						"txt",
						"undotree",
						"vimwiki",
						"vista",
					},
					buftype_exclude = { "terminal", "nofile" },
					show_trailing_blankline_indent = false,
					show_current_context = true,
					context_patterns = {
						"^if",
						"^table",
						"block",
						"class",
						"for",
						"function",
						"if_statement",
						"import",
						"list_literal",
						"method",
						"selector",
						"type",
						"var",
						"while",
					},
					space_char_blankline = " ",
				},
			},
		},
		build = ":TSUpdate",
		event = { "BufReadPost", "BufNewFile" },
		config = require("plugins.treesitter.config"),
	},
}
